<?php

return [
    "Alba Iulia",
    "Arad",
    "Bacău",
    "Bălți",
    "Baia Mare",
    "București",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Buzău",
    "Călărași",
    "Cluj-Napoca",
    "Constanța",
    "Craiova",
    "Deva",
    "Drobeta-Turnu Severin",
    "Făgăraș",
    "Galați",
    "Giurgiu",
    "Târgu Jiu",
    "Hunedoara",
    "Iași",
    "Miercurea Ciuc",
    "Oradea",
    "Pitești",
    "Ploiești",
    "Râmnicu Vâlcea",
    "Satu Mare",
    "Sibiu",
    "Sighișoara",
    "Slatina",
    "Suceava",
    "Târgu Mureș",
    "Timișoara",
    "Tulcea",
    "Vaslui",
    "Zalău"
];
